version: '3.8'

services:
  cinema-brest:
    build: .
    container_name: cinema-brest
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      # Persister la base de données SQLite
      - ./data:/app/data
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - TIMEZONE=Europe/Paris
      # Ajoutez votre clé API Jawg ici
      - JAWG_API_KEY=${JAWG_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
